### ISSUE TITLE
Where is 1.5.3?

### ISSUE THREAD

**Issue by jonjongames1997** [blockba5her/nearest-postal#16]
I keep getting an update message saying "nearest-postal 1.5.3 update is available" but no 1.5.3 release on github. Where to get 1.5.3?

**Comment by Im-Your-Papi** [comment]
> I keep getting an update message saying "nearest-postal 1.5.3 update is available" but no 1.5.3 release on github. Where to get 1.5.3?

There's none. Maybe their brain got a 1.5.3 xD
