### ISSUE TITLE
Does not start when server restarts

### ISSUE THREAD

**Issue by Lukeiscooler** [blockba5her/nearest-postal#17]
So every time I restart my server it doesn't automatically start when I get back in server so I manually have to start it any way I can fix this ?

**Comment by DevBlocky** [comment]
Put the script in the `server.cfg`

**Comment by Lukeiscooler** [comment]
> Put the script in the `server.cfg`

I did that and still won't work without doing that as well and I did download the new release as well

**Comment by Lukeiscooler** [comment]
I got it found out the problem! It actually wasn't in the server.cfg
