### ISSUE TITLE
Not rendering the map

### ISSUE THREAD

**Issue by Keyygan** [blockba5her/nearest-postal#5]
Hello,

I have it installed on my server and have not messed with anything in the config except the location of the nearest postal to be next to the map. 

My issue is that the postals do not show up on the map and it is still using the regular fivem map. I kinda feel stupid and I do think its simple I just cannot figure out why its not working.. 

All help is appreciated. Thanks!

**Comment by blockba5her** [comment]
This script doesn't provide the postal map itself, only the text next to your minimap that shows your closest postal:

![this](https://i.imgur.com/YZPCeLV.png)

To get the postal maps themselves, here are the ones supported by the script:
- [Classic Postal Map](https://forum.fivem.net/t/release-modified-street-names-w-postal-numbers/8717)
- [Improved Postal Map](https://forum.fivem.net/t/release-postal-code-map-new-improved-v1-1/147458)
- [OCRP Postal Map](https://forum.fivem.net/t/release-ocrp-community-releases/166277)

There are more maps on the Cfx.re forums, but these are the ones that will work with this script. Hopefully this answers your question :smile:
